name: rating
description: RatingProject
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  firebase_core: ^2.19.0
  cloud_firestore: ^4.11.0
  flutterfire_ui: ^0.4.3+20
  firebase_auth: ^4.11.1
  sign_in_with_apple: ^3.3.0
  flutter_bloc: ^8.1.3
  dio: ^5.3.3
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  retrofit: ^4.0.3
  get_it: ^7.6.4
  injectable: ^2.3.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  retrofit_generator: ^8.0.3
  injectable_generator: ^2.4.1
  mocktail: ^1.0.1
  bloc_test: ^9.1.5
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/AppIcon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/AppIcon.png"

flutter:
  uses-material-design: true
  assets:
   - assets/graphics/
   - assets/icons/
   - assets/graphics/artists_avatars/
   - assets/graphics/artists_avatars/
   - assets/graphics/artists_avatars/artist_cover_1/ 
   - assets/graphics/artists_avatars/artist_cover_2/
   - assets/graphics/artists_avatars/artist_cover_3/
   - assets/graphics/artists_avatars/artist_cover_4/
   - assets/graphics/artists_avatars/artist_cover_5/
   - assets/graphics/podcasters_avatars/podcaster_cover_1/
   - assets/graphics/podcasters_avatars/podcaster_cover_2/
   - assets/graphics/podcasters_avatars/podcaster_cover_3/
   - assets/graphics/podcasters_avatars/podcaster_cover_4/
   - assets/graphics/podcasters_avatars/podcaster_cover_5/