name: rating
description: RatingProject
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  firebase_core: ^2.19.0
  cloud_firestore: ^4.11.0
  flutterfire_ui: ^0.4.3+20
  firebase_auth: ^4.11.1
  sign_in_with_apple: ^3.3.0
  flutter_bloc: ^8.1.3
  dio: ^5.3.3
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
   - assets/icons/
   - assets/avatars/
   - assets/album_covers/